post http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxNDcyNmYzNjk3YmI5MTBlMDA1MDhjYyIsImlhdCI6MTYzMjY0MzA4M30.05jY1ZymML1C3PAY7JLMPyVufY7G20qA6A5Iy3IGXdw

{
    "tema":"Oggi ultima notte finalmente",
    "important":true,
    "giorno":"2021-01-22T08:15:36.196+00:00",
    "ora":"22:00",
    "userId":"6147273a697bb910e00508ce"
}